/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab_05_Main */

#ifndef _Included_lab_05_Main
#define _Included_lab_05_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab_05_Main
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_lab_105_Main_multi01
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     lab_05_Main
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_lab_105_Main_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     lab_05_Main
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lab_105_Main_multi03
  (JNIEnv *, jobject);

/*
 * Class:     lab_05_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lab_105_Main_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
